package br.com.bwstock.view;

import br.com.bwstock.BwStock;

public class PainelPrincipal extends javax.swing.JFrame {

    public PainelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        painelFundoInferior = new javax.swing.JPanel();
        panelProduto = new javax.swing.JPanel();
        textoProduto = new javax.swing.JLabel();
        iconProduto = new javax.swing.JLabel();
        panelEntrada = new javax.swing.JPanel();
        textoEntrada = new javax.swing.JLabel();
        iconEntrada = new javax.swing.JLabel();
        panelSaida = new javax.swing.JPanel();
        textoSaida = new javax.swing.JLabel();
        iconSaida = new javax.swing.JLabel();
        panelInventario = new javax.swing.JPanel();
        textoInventario = new javax.swing.JLabel();
        iconInventario = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JLabel();
        iconUsuario = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        textoCategoria = new javax.swing.JLabel();
        iconCategoria = new javax.swing.JLabel();
        panelLogoEmpresa = new javax.swing.JPanel();
        textoLogoEmpresa = new javax.swing.JLabel();
        textoDescricaoEmpresa = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelFundo.setBackground(new java.awt.Color(45, 118, 232));

        painelFundoInferior.setBackground(new java.awt.Color(255, 255, 255));

        panelProduto.setPreferredSize(new java.awt.Dimension(133, 103));
        panelProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProdutoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelProdutoMousePressed(evt);
            }
        });

        textoProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoProduto.setForeground(new java.awt.Color(45, 118, 232));
        textoProduto.setText("PRODUTO");

        iconProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/product_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelProdutoLayout = new javax.swing.GroupLayout(panelProduto);
        panelProduto.setLayout(panelProdutoLayout);
        panelProdutoLayout.setHorizontalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoProduto)
                    .addGroup(panelProdutoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(iconProduto)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelProdutoLayout.setVerticalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoProduto)
                .addGap(18, 18, 18))
        );

        panelEntrada.setPreferredSize(new java.awt.Dimension(133, 103));
        panelEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEntradaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelEntradaMousePressed(evt);
            }
        });

        textoEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoEntrada.setForeground(new java.awt.Color(45, 118, 232));
        textoEntrada.setText("ENTRADA");

        iconEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/entrada_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelEntradaLayout = new javax.swing.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(textoEntrada)
                .addGap(31, 31, 31))
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(iconEntrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoEntrada)
                .addGap(18, 18, 18))
        );

        panelSaida.setPreferredSize(new java.awt.Dimension(133, 103));
        panelSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSaidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSaidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSaidaMousePressed(evt);
            }
        });

        textoSaida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoSaida.setForeground(new java.awt.Color(45, 118, 232));
        textoSaida.setText("SAIDA");

        iconSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/saida_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelSaidaLayout = new javax.swing.GroupLayout(panelSaida);
        panelSaida.setLayout(panelSaidaLayout);
        panelSaidaLayout.setHorizontalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaidaLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSaida)
                    .addComponent(textoSaida))
                .addGap(41, 41, 41))
        );
        panelSaidaLayout.setVerticalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaidaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(iconSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(textoSaida)
                .addGap(17, 17, 17))
        );

        panelInventario.setPreferredSize(new java.awt.Dimension(133, 103));
        panelInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelInventarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelInventarioMousePressed(evt);
            }
        });

        textoInventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoInventario.setForeground(new java.awt.Color(45, 118, 232));
        textoInventario.setText("INVENTARIO");

        iconInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/inventario_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(textoInventario))
                    .addGroup(panelInventarioLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(iconInventario)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(iconInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoInventario)
                .addGap(18, 18, 18))
        );

        panelUsuario.setPreferredSize(new java.awt.Dimension(133, 103));
        panelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelUsuarioMousePressed(evt);
            }
        });

        textoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(45, 118, 232));
        textoUsuario.setText("USUARIO");

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/usuario_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoUsuario)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(iconUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(iconUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoUsuario)
                .addGap(13, 13, 13))
        );

        panelCategoria.setPreferredSize(new java.awt.Dimension(133, 103));
        panelCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCategoriaMousePressed(evt);
            }
        });

        textoCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoCategoria.setForeground(new java.awt.Color(45, 118, 232));
        textoCategoria.setText("CATEGORIA");

        iconCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bwstock/img/inventario_48x48.png"))); // NOI18N

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(iconCategoria))
                    .addGroup(panelCategoriaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(textoCategoria)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoCategoria)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout painelFundoInferiorLayout = new javax.swing.GroupLayout(painelFundoInferior);
        painelFundoInferior.setLayout(painelFundoInferiorLayout);
        painelFundoInferiorLayout.setHorizontalGroup(
            painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoInferiorLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(panelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoInferiorLayout.createSequentialGroup()
                        .addComponent(panelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        painelFundoInferiorLayout.setVerticalGroup(
            painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoInferiorLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(panelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(panelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(panelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelFundoInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        panelLogoEmpresa.setBackground(new java.awt.Color(45, 118, 232));

        textoLogoEmpresa.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textoLogoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        textoLogoEmpresa.setText("BW-STOCK");

        textoDescricaoEmpresa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textoDescricaoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        textoDescricaoEmpresa.setText("Gerenciador de Estoque");

        textoTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo.setText("Acesso Principal");

        javax.swing.GroupLayout panelLogoEmpresaLayout = new javax.swing.GroupLayout(panelLogoEmpresa);
        panelLogoEmpresa.setLayout(panelLogoEmpresaLayout);
        panelLogoEmpresaLayout.setHorizontalGroup(
            panelLogoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoEmpresaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelLogoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogoEmpresaLayout.createSequentialGroup()
                        .addComponent(textoLogoEmpresa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLogoEmpresaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoDescricaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(textoTitulo)))
                .addContainerGap())
        );
        panelLogoEmpresaLayout.setVerticalGroup(
            panelLogoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoEmpresaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoLogoEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLogoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDescricaoEmpresa)
                    .addComponent(textoTitulo))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundoInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addComponent(panelLogoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addComponent(panelLogoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelFundoInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProdutoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProdutoMouseEntered

    private void panelProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProdutoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProdutoMouseExited

    private void panelProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProdutoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelProdutoMousePressed

    private void panelEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntradaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntradaMouseEntered

    private void panelEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntradaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntradaMouseExited

    private void panelEntradaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEntradaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEntradaMousePressed

    private void panelSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaidaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelSaidaMouseEntered

    private void panelSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaidaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelSaidaMouseExited

    private void panelSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaidaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelSaidaMousePressed

    private void panelInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInventarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelInventarioMouseEntered

    private void panelInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInventarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelInventarioMouseExited

    private void panelInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInventarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelInventarioMousePressed

    private void panelUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUsuarioMouseEntered

    private void panelUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUsuarioMouseExited

    private void panelUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUsuarioMousePressed

    private void panelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsuarioMouseClicked
        BwStock.JanelaUsuario();
    }//GEN-LAST:event_panelUsuarioMouseClicked

    private void panelSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSaidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelSaidaMouseClicked

    private void panelProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProdutoMouseClicked
        BwStock.JanelaProduto();
    }//GEN-LAST:event_panelProdutoMouseClicked

    private void panelCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCategoriaMouseEntered

    private void panelCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCategoriaMouseExited

    private void panelCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCategoriaMousePressed

    private void panelCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseClicked
        // TODO add your handling code here:
        BwStock.JanelaCategoria();
        
    }//GEN-LAST:event_panelCategoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCategoria;
    private javax.swing.JLabel iconEntrada;
    private javax.swing.JLabel iconInventario;
    private javax.swing.JLabel iconProduto;
    private javax.swing.JLabel iconSaida;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelFundoInferior;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelLogoEmpresa;
    private javax.swing.JPanel panelProduto;
    private javax.swing.JPanel panelSaida;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JLabel textoCategoria;
    private javax.swing.JLabel textoDescricaoEmpresa;
    private javax.swing.JLabel textoEntrada;
    private javax.swing.JLabel textoInventario;
    private javax.swing.JLabel textoLogoEmpresa;
    private javax.swing.JLabel textoProduto;
    private javax.swing.JLabel textoSaida;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoUsuario;
    // End of variables declaration//GEN-END:variables
}
